---
- name: Install plattform app
  copy:
    src: "{{ app.src }}"
    dest: "{{ app.home }}"
    remote_src: "{{ app.remote_src }}"
 
- name: Symlink current app version
  file:
    src: "{{ app.home }}/{{ app.src | basename }}"
    dest:  "{{ app.home }}/tailoringexpert-exec.jar"
    state: link         
              
- name: Install SSL certificate
  copy:
    src: "{{ app.ssl.src }}"
    dest:  "{{ app.lib }}"
    remote_src: no   
    
- name: Copy plattform required libs
  copy:
    src: "{{ item.src }}"
    dest:  "{{ app.lib }}"
    remote_src: "{{ item.remote_src }}"
  loop: "{{ app.libs }}"  
  
- name: Create application.properties
  template:
    src: application.properties.j2
    dest:  "{{ app.config }}/application.properties"
    mode: 0640    
  
- name: Create logging config
  template:
    src: log4j2.xml.j2
    dest:  "{{ app.config }}/log4j2.xml"
    mode: 0640
           
- name: Create startscript
  template:
    src: start.sh.j2
    dest:  "{{ app.service }}/start.sh"
    mode: 0755

- include_tasks: 
    file: service.yml
 