---
- name: restart app
  service: 
    name: tailoringexpert
    state: restarted
    enabled: true
  become: true
  remote_user: "{{ sudo_user }}"
  notify: wait for app
  
- name: wait for app
  uri:
    url: "https://localhost:{{app_serverport}}/api/actuator/info"
    method: GET
    validate_certs: false
  register: _result
  until: _result.status == 200
  retries: 24
  delay: 5
